version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    # restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nurturingdiscoveries
      MYSQL_USER: root
      MYSQL_PASSWORD: root
   
  server:
    build: ./Server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/server
    environment:
      NODE_ENV: production
    depends_on:
      - mysqldb

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/src/main
    environment:
      NODE_ENV: production

volumes:
  db_data:
